#!/bin/sh
# atrun uid=1000 gid=1000
# mail appuser 0
umask 22
SHELL=/bin/sh; export SHELL
HOME=/home/appuser; export HOME
PATH=/usr/local/bin:/usr/bin:/bin; export PATH
cd /home/appuser || {
	echo 'Execution directory inaccessible' >&2
	exit 1
}
/usr/local/bin/run-migration.sh --stage=final
echo "migration complete"
