title: inspectah
description: Migration analysis and image build tool for package-mode to image-mode RHEL
remote_theme: just-the-docs/just-the-docs@v0.10.0

url: ""
baseurl: "/inspectah"

search_enabled: true
search:
  heading_level: 3

color_scheme: dark

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/marrusl/inspectah"
gh_edit_branch: "main"
gh_edit_source: docs
gh_edit_view_mode: "tree"

aux_links:
  "GitHub":
    - "https://github.com/marrusl/inspectah"

plugins:
  - jekyll-remote-theme
